export const homePage = {
  key: 'home',
  title: 'Accueil',
  status: 'published',
  sections: {
    hero: {
      eyebrow: 'Studio digital · Libreville',
      title: 'Le numérique qui fait avancer votre organisation.',
      highlight: 'avancer',
      text: 'Nous concevons des produits et services numériques simples, robustes et adaptés aux réalités de votre activité.',
      primaryCta: { label: 'Démarrer un projet', path: '/devis' },
      secondaryCta: { label: 'Voir nos réalisations', path: '/realisations' },
      trust: ['Stratégie', 'Design', 'Technologie', 'Accompagnement'],
      image: '/images/heroes/team.jpg',
    },
    expertise: {
      eyebrow: 'Notre expertise',
      title: 'Un partenaire pour chaque étape de votre projet.',
      text: 'De la réflexion au déploiement, nous réunissons les compétences nécessaires pour construire des solutions qui fonctionnent.',
      link: '/services',
    },
    method: {
      eyebrow: 'Notre méthode',
      title: 'Simple dans l’approche. Exigeante dans l’exécution.',
      steps: [
        { number: '01', title: 'Comprendre', text: 'Nous clarifions vos objectifs, vos utilisateurs et les contraintes du projet.' },
        { number: '02', title: 'Concevoir', text: 'Nous transformons les besoins en une expérience simple et une solution solide.' },
        { number: '03', title: 'Construire', text: 'Nous développons par étapes, avec des validations régulières et concrètes.' },
        { number: '04', title: 'Faire évoluer', text: 'Nous suivons le produit après son lancement et l’améliorons avec vous.' },
      ],
    },
    projects: {
      eyebrow: 'Réalisations',
      title: 'Des solutions pensées pour le terrain.',
      text: 'Quelques exemples de produits numériques conçus pour répondre à des enjeux concrets.',
      link: '/realisations',
    },
    values: {
      eyebrow: 'Pourquoi DevGroup',
      title: 'La technologie n’est utile que lorsqu’elle sert vraiment les personnes.',
      items: [
        'Une compréhension fine de vos enjeux',
        'Des choix techniques durables',
        'Une collaboration claire et transparente',
        'Un accompagnement au-delà du lancement',
      ],
    },
    blog: {
      eyebrow: 'Perspectives',
      title: 'Nos dernières réflexions.',
      link: '/blog',
      linkLabel: 'Voir le blog',
    },
  },
}

export const catalogItems = [
  {
    type: 'service',
    slug: 'developpement-solutions-numeriques',
    title: 'Développement de solutions numériques',
    icon: 'Code2',
    description: 'Conception et réalisation de plateformes et applications sur mesure adaptées à vos besoins.',
    order: 1,
    details: {
      eyebrow: 'Services',
      title: 'Des solutions métiers construites autour de vos usages.',
      bullets: ['Applications web', 'Applications mobiles', 'Logiciels métiers', 'Plateformes SaaS', 'Portails clients', 'Outils de gestion interne', 'Modernisation d’applications', 'Applications de bureau'],
    },
  },
  {
    type: 'service',
    slug: 'creation-sites-web',
    title: 'Création de sites web',
    icon: 'Globe2',
    description: 'Conception de sites professionnels adaptés aux besoins des entreprises et organisations.',
    order: 2,
    details: {
      eyebrow: 'Services',
      title: 'Une présence web claire, professionnelle et maintenable.',
      bullets: ['Sites vitrines', 'Sites institutionnels', 'Blogs professionnels', 'Portails d’information', 'Sites événementiels', 'Refonte de sites', 'Maintenance'],
    },
  },
  {
    type: 'service',
    slug: 'digitalisation-entreprises',
    title: 'Digitalisation des entreprises',
    icon: 'RefreshCw',
    description: 'Remplacement des processus manuels par des solutions numériques simples et efficaces.',
    order: 3,
    details: {
      eyebrow: 'Services',
      title: 'Des processus plus fluides, mieux suivis et moins dépendants du papier.',
      bullets: ['Analyse des processus métiers', 'Solutions de gestion', 'Formation des équipes', 'Gestion documentaire', 'Tableaux de bord'],
    },
  },
  {
    type: 'service',
    slug: 'conception-ui-ux',
    title: 'Conception UI/UX',
    icon: 'Palette',
    description: 'Création d’interfaces modernes, intuitives et centrées utilisateur.',
    order: 4,
    details: {
      eyebrow: 'Services',
      title: 'Des interfaces utiles, lisibles et faciles à adopter.',
      bullets: ['Maquettes d’applications', 'Maquettes de sites web', 'Prototypage interactif', 'Design system', 'Optimisation UX', 'Visuels et affiches sur mesure', 'Formation des équipes'],
    },
  },
  {
    type: 'service',
    slug: 'hebergement-deploiement',
    title: 'Hébergement et déploiement',
    icon: 'CloudCog',
    description: 'Mise en production et gestion des infrastructures applicatives, avec hébergement local lorsque c’est pertinent.',
    order: 5,
    details: {
      eyebrow: 'Services',
      title: 'Une mise en ligne maîtrisée et un socle technique fiable.',
      bullets: ['Déploiement de plateformes web', 'Gestion de serveurs', 'Configuration de domaines', 'Surveillance des services', 'Hébergement local des solutions développées'],
    },
  },
  {
    type: 'service',
    slug: 'maintenance-support',
    title: 'Maintenance et support',
    icon: 'Headphones',
    description: 'Assistance technique après livraison pour garder vos projets stables et performants.',
    order: 6,
    details: {
      eyebrow: 'Services',
      title: 'Un accompagnement technique après la mise en ligne.',
      bullets: ['Correction de bugs', 'Mises à jour', 'Assistance utilisateur', 'Optimisation des performances', 'Évolution fonctionnelle'],
    },
  },
  {
    type: 'service',
    slug: 'intelligence-artificielle',
    title: 'Intelligence artificielle',
    icon: 'BrainCircuit',
    description: 'Intégrez la puissance de l’IA dans vos processus métiers et vos outils internes.',
    order: 7,
    details: {
      eyebrow: 'Services',
      title: 'Des usages IA concrets pour automatiser, analyser et assister vos équipes.',
      bullets: ['Chatbots et agents IA', 'Modèles d’aide à la décision', 'Analyse prédictive et business', 'Assistant IA WhatsApp', 'Automatisation intelligente des processus métier', 'Systèmes IA multimodaux intelligents'],
    },
  },
  {
    type: 'service',
    slug: 'conseil-transformation-numerique',
    title: 'Conseil en transformation numérique',
    icon: 'Compass',
    description: 'Accompagnement stratégique des organisations dans leurs projets numériques.',
    order: 8,
    details: {
      eyebrow: 'Services',
      title: 'Des décisions numériques cadrées, réalistes et alignées avec vos objectifs.',
      bullets: ['Audit numérique', 'Étude de faisabilité', 'Élaboration de cahiers des charges', 'Accompagnement de projets', 'Choix technologiques', 'Assistance à la maîtrise d’ouvrage'],
    },
  },
  {
    type: 'service',
    slug: 'synthese-vocale-voix-ia',
    title: 'Synthèse vocale et voix IA',
    icon: 'AudioLines',
    description: 'Création de voix professionnelles pour spots radio, SVI, e-learning et applications. Bientôt disponible.',
    order: 9,
    details: {
      eyebrow: 'Services bientôt disponible',
      title: 'Des expériences vocales professionnelles pour vos contenus et applications.',
      bullets: ['Synthèse vocale IA', 'Spots audio et publicités radio', 'Voix pour applications et chatbots', 'Clonage de voix professionnelles', 'Serveurs vocaux intelligents (SVI)', 'Contenu audio en langues locales'],
    },
  },
  { type: 'solution', slug: 'portail-entreprise', title: 'Portail entreprise', icon: 'Blocks', description: 'Centralisez les ressources, les échanges et les outils de vos équipes.', order: 1 },
  { type: 'solution', slug: 'application-metier', title: 'Application métier', icon: 'BriefcaseBusiness', description: 'Digitalisez précisément les processus qui font la valeur de votre organisation.', order: 2 },
  { type: 'solution', slug: 'espace-client', title: 'Espace client', icon: 'MonitorSmartphone', description: 'Offrez à vos clients un accès simple, autonome et sécurisé à vos services.', order: 3 },
  { type: 'solution', slug: 'e-commerce', title: 'E-commerce', icon: 'ShoppingCart', description: 'Vendez en ligne grâce à une expérience fluide et adaptée à votre marché.', order: 4 },
  { type: 'solution', slug: 'automatisation-processus', title: 'Automatisation', icon: 'Bot', description: 'Réduisez les tâches répétitives et libérez du temps pour les activités essentielles.', order: 5 },
  { type: 'solution', slug: 'tableaux-de-bord', title: 'Tableaux de bord', icon: 'BarChart3', description: 'Transformez vos données en indicateurs utiles pour mieux décider.', order: 6 },
  { type: 'solution', slug: 'integrations-api', title: 'Intégrations API', icon: 'LayoutDashboard', description: 'Connectez vos logiciels et faites circuler les données sans friction.', order: 7 },
]

export const legacyServiceSlugs = [
  'transformation-digitale',
  'developpement-web',
  'developpement-mobile',
  'plateformes-metiers',
  'ux-ui-design',
  'cloud-devops',
  'conseil-it',
]

export const projects = [
  { slug: 'gestion-scolaire', title: 'Plateforme de gestion scolaire', type: 'EdTech', color: 'orange', description: 'Un espace unifié pour les élèves, parents et équipes pédagogiques.', order: 1 },
  { slug: 'suivi-logistique', title: 'Solution de suivi logistique', type: 'Logistique', color: 'blue', description: 'Une visibilité en temps réel sur les opérations et les livraisons.', order: 2 },
  { slug: 'portail-services', title: 'Portail de services citoyens', type: 'GovTech', color: 'green', description: 'Des démarches administratives plus simples et accessibles en ligne.', order: 3 },
]

export const posts = [
  {
    slug: 'reussir-transformation-digitale',
    category: 'Stratégie',
    title: 'Réussir sa transformation digitale en Afrique',
    publishedAt: new Date('2026-06-04T09:00:00.000Z'),
    description: 'Les principes pratiques pour construire une transformation adaptée à son marché.',
    body: 'Le contenu complet de cet article sera bientôt disponible. Cette page pose déjà la structure nécessaire pour publier les futurs contenus depuis l’espace d’administration.\n\nUne approche numérique efficace part toujours des objectifs réels, des utilisateurs et du contexte opérationnel.',
  },
  {
    slug: 'choisir-application-metier',
    category: 'Produit',
    title: 'Quand faut-il créer une application métier ?',
    publishedAt: new Date('2026-05-21T09:00:00.000Z'),
    description: 'Les signaux qui indiquent qu’un outil sur mesure devient un investissement pertinent.',
    body: 'Un outil métier devient pertinent lorsque les processus critiques ne peuvent plus être correctement servis par les solutions génériques.',
  },
  {
    slug: 'ux-services-numeriques',
    category: 'Design',
    title: 'L’UX au service de produits numériques adoptés',
    publishedAt: new Date('2026-05-08T09:00:00.000Z'),
    description: 'Pourquoi une bonne expérience utilisateur est d’abord une question de compréhension.',
    body: 'Une bonne expérience utilisateur commence par une compréhension nette des personnes, de leurs contraintes et de leurs objectifs.',
  },
]
